INSERT INTO races(idRace,nomRace) VALUES
(1,'Akita Inu'),
(2,'Cao Da Estrela'), 
(3,'Labrador'),
(4,'Am staff'),	 
(5,'Cao de Gado Transmontano'),	 
(6,'Lagotto romagnolo'),
(7,'Barbet'),	 
(8,'Carlin'),	 
(9,'Lapplund'),
(10,'Basset Artésien'),	 
(11,'Cavalier King Charles'),	 
(12,'Léonberg'),
(13,'Basset Fauve De Br.'),
(14,'Cesky Terrier'),	 
(15,'Lévrier Afghan'),
(16,'Basset Hound'),	 
(17,'Charplaninatz'),	
(18,'Lhassa Apso'),
(19,'Beagle'),	  
(20,'Chien Berger Polonais'),	 
(21,'Manchester Terrier'),
(22,'Bearded Collie'),  
(23,'Chien chinois'),	 
(24,'Mastiff'),
(25,'Beauceron'),	  
(26,'Chien du Pérou'),	 
(27,'Mâtin de Naples'),
(28,'Bedlington Terrier'),	  
(29,'Chien Loup'),	 
(30,'Mâtin Espagnol'),
(31,'Berger Allemand'),	 
(32,'Chihuahua'),	 
(33,'Montagne de Pyrénées'),
(34,'Berger Australien'),	 
(35,'Chow Chow'),	 
(36,'Parson Russell Terrier'),
(37,'Berger d Anatolie'),	  
(38,'Clumber'),	 
(39,'Pékinois'),
(40,'Berger Finnois'),	 
(41,'Cocker Anglais'),	 
(42,'Pinscher nain'),
(43,'Bichon Bolonais'),	 
(44,'Colley'),	 
(45,'Presa Mallorquin'),
(46,'Bichon frisé'),	 
(47,'Coton de Tuléar'),	 
(48,'Rottweiler'),
(49,'Bichon Havanais'),	 
(50,'Dalmatien'),	 
(51,'Saint Hubert'),
(52,'Bichon Maltais'),	 
(53,'Dobermann'),	  
(54,'Samoyède'),
(55,'Bobtail'),	 
(56,'Dogue Allemand'),	 
(57,'Schapendoes'),
(58,'Border Collie'),	 
(59,'Dogue Argentin'),	 
(60,'Schipperke'),
(61,'Border Terrier'),	 
(62,'Dogue de Bordeaux'),	 
(63,'Schnauzer Nain'),
(64,'Bouledogue Français'),	 
(65,'Épagneul Breton'),	 
(66,'Scottish Terrier'),
(67,'Bouvier Australien'),	 
(68,'Épagneul français'),	 
(69,'Sealyham Terrier'),
(70,'Bouvier Bernois'),	 
(71,'Épagneul Tibétain'),	 
(72,'Setter Gordon'),
(73,'Bouvier des Flandres'),	  
(74,'Eurasier'),	 
(75,'Shar pei'),
(76,'Boxer'),	  
(77,'Fila Brasilero'),	 
(78,'Shetland'),
(79,'Braque allemand'),  
(80,'Flat Coated Retriever'),	 
(81,'Shiba Inu'),
(82,'Braque d Auvergne'),	  
(83,'Fox-Terrier à poil lisse'),	 
(84,'Shih Tzu'),
(85,'Braque du Bourbonnais'),	  
(86,'Golden Retriever'),	 
(87,'Silky Terrier'),
(88,'Braque de Weimar'),	  
(89,'Hovawart'),	 
(90,'Spitz'),
(91,'Braque Saint Germain'),	  
(92,'Husky Sibérien'),	  
(93,'Spitz Loup'),
(94,'Briard'),	  
(95,'Irish Terrier'),	  
(96,'Teckel'),
(97,'Bulldog'),	  
(98,'Jack Russell Terrier'),	 
(99,'Terre Neuve'),
(100,'Bull Terrier'),	  
(101,'Kelpie'),	 
(102,'Terrier Tibétain'),
(103,'CairnTerrier'),	  
(104,'Kerry Blue Terrier'),	 
(105,'Westie'),
(106,'Cane Corso'),	  
(107,'Komondor'),	 
(108,'Whippet'),
(109,'Caniche'),	 	 
(110,'Yorkshire');