
INSERT INTO regions(idRegion,codeRegion,nomRegion) VALUES
  (1,'FR-ARA', 'Auvergne-Rhône-Alpes'),
  (2,'FR-BFC', 'Bourgogne-Franche-Comté'),
  (3,'FR-BRE', 'Bretagne'),
  (4,'FR-CVL', 'Centre-Val de Loire'),
  (5,'FR-COR', 'Corse'),
  (6,'FR-GES', 'Grand Est'),
  (7,'FR-HDF', 'Hauts-de-France'),
  (8,'FR-IDF', 'Île-de-France'),
  (9,'FR-NOR', 'Normandie'),
  (10,'FR-NAQ', 'Nouvelle-Aquitaine'),
  (11,'FR-OCC', 'Occitanie'),
  (12,'FR-PDL', 'Pays de la Loire'),
  (13,'FR-PAC', 'Provence-Alpes-Côte d''Azur'),
  (14,'FR-GP'	, 'Guadeloupe'),
  (15,'FR-GF', 'Guyane'),
  (16,'FR-MQ', 'Martinique'),
  (17,'FR-RE', 'La Réunion'),
  (18,'FR-YT', 'Mayotte');